project:
  type: website

website:
  title: "Spotify qmd tutorial dashboard"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: qmd_dashboard.qmd
        text: Dashboard

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true
